language: java
jdk:
  - openjdk6

after_success:
 # Deploy new versions to Nexus
 # Based on http://blog.xeiam.com/2013/05/configure-travis-ci-to-deploy-snapshots.html
 # - "git clone -b travis `git config --get remote.origin.url` target/travis"
 # - "mvn source:jar javadoc:jar deploy -DskipTests=true --settings target/travis/settings.xml -B"
 # Trigger dependent builds
 - "gem install travis"
 - "for dep in $CI_DEPENDENT_BUILDS; do travis restart -r $dep; done"

# whitelist
branches:
  only:
    - master
    - "2.3"

env:
  global:
    # Define dependent builds
    - "CI_DEPENDENT_BUILDS=\"FasterXML/jackson-module-scala\""
    - secure: "ZIFMeNzZCvLYWICiUyHFSm8Ypz6lYFbF/+LGz6a+Sh8B9tSnvYvlrE4gSFJj3NzRWY0RG/vizoyFEpVgxOnzXDMLuuy/dreupnHR1FfVmiaiceK4JHRwAzl0lQzr2hdVwJbqpX0GfrxKmbg8Jvv9WPKtfM6X4167ElVj4O/8IRc="
    - secure: "VOC/J8eFbM2OeysBp0Gx0G73MySRATCoN7hc9Ok0kJXE/dbE/2KOoFlTwwxUgErwJXkjJKKXafYcbq/22S7wkaoDW5XAvplSu3skxdE0NRGVzozcDMXO5UoGlt9Ti4XIBMCvy7bB/NO+J5IgNedCtcNnBsrGZCdodW3DTYtqQLs="

